// export const host = "https://cs5500-proj-server.onrender.com";
export const host = "http://localhost:4000";
export const profileRoute = `${host}/api/userProfile`;
export const planRoute = `${host}/api/plans`;
export const getPlanRoute = `${host}/api//userPlan`;
export const planProgress = `${host}/api/progress`;
export const getUser = `${host}/api/users`;
export const getLikedExercise = `${host}/api/userExercise`;
export const videoRoute = `${host}/api/videos`;
